#include "utils.h"

PROPERTY_HIT_RATE(PHYSICAL, physical);
PROPERTY_HIT_RATE(ICE, ice);
PROPERTY_HIT_RATE(FIRE, fire);
PROPERTY_HIT_RATE(LIGHTNING, lightning);
PROPERTY_HIT_RATE(WIND, wind);
PROPERTY_HIT_RATE(QUANTUM, quantum);
PROPERTY_HIT_RATE(IMAGINARY, imaginary);

